### ISSUE TITLE
안녕하세요! 리버싱 공부중인 취준생입니다.

### ISSUE THREAD

**Issue by HongKyoungIn** [Kim-Tae-Yeong/Coding-Test#1]
legends0427 velog 블로그가 너무 잘 정리 되어 있어서 참고하여 공부하고 있었는데 게시물이 전부 사라졌는데 혹시 무슨 일 있으신건가요?

**Comment by Kim-Tae-Yeong** [comment]
제가 리버싱보다는 개발쪽을 공부할 계획이라 더이상 글을 쓰지 않을거 같아서 다 지우게 되었습니다.

**Comment by HongKyoungIn** [comment]
아예 지우신건가요? 아니면 비공개인가요?
그리고 혹시 게시물 작성할 때 쓰신 그림들 어디서 받아오셨나요? 저도 리버싱 블로그 작성중인데 그림을 넣고싶은데 어디서 소스를 구하셨을까요?
